// <auto-generated />
using System;
using DataAcessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAcessLayer.Migrations
{
    [DbContext(typeof(AllDbContext))]
    [Migration("20250606165259_AddSeedingsForShapes")]
    partial class AddSeedingsForShapes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAcessLayer.ModelsCalculator.Calculator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("Operand1")
                        .HasColumnType("float");

                    b.Property<double?>("Operand2")
                        .HasColumnType("float");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<double>("Result")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Calculations");
                });

            modelBuilder.Entity("DataAcessLayer.ModelsRPS.RPS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComputerMove")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePlayed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerMove")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("RpsGames");
                });

            modelBuilder.Entity("DataAcessLayer.ModelsShapes.Shape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("Perimeter")
                        .HasColumnType("float");

                    b.Property<string>("ShapeType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Shapes");

                    b.HasDiscriminator<string>("ShapeType").HasValue("Shape");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DataAcessLayer.ModelsShapes.Parallelogram", b =>
                {
                    b.HasBaseType("DataAcessLayer.ModelsShapes.Shape");

                    b.Property<double>("BaseLength")
                        .HasColumnType("float");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("SideLength")
                        .HasColumnType("float");

                    b.ToTable("Shapes", t =>
                        {
                            t.Property("Height")
                                .HasColumnName("Parallelogram_Height");

                            t.Property("SideLength")
                                .HasColumnName("Parallelogram_SideLength");
                        });

                    b.HasDiscriminator().HasValue("Parallelogram");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Area = 32.0,
                            DateCreated = new DateTime(2024, 6, 7, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Perimeter = 28.0,
                            BaseLength = 8.0,
                            Height = 4.0,
                            SideLength = 6.0
                        });
                });

            modelBuilder.Entity("DataAcessLayer.ModelsShapes.Rectangle", b =>
                {
                    b.HasBaseType("DataAcessLayer.ModelsShapes.Shape");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.ToTable("Shapes", t =>
                        {
                            t.Property("Height")
                                .HasColumnName("Rectangle_Height");
                        });

                    b.HasDiscriminator().HasValue("Rectangle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 50.0,
                            DateCreated = new DateTime(2024, 6, 7, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Perimeter = 30.0,
                            Height = 5.0,
                            Width = 10.0
                        });
                });

            modelBuilder.Entity("DataAcessLayer.ModelsShapes.Rhombus", b =>
                {
                    b.HasBaseType("DataAcessLayer.ModelsShapes.Shape");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("SideLength")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Rhombus");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Area = 21.0,
                            DateCreated = new DateTime(2024, 6, 7, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Perimeter = 28.0,
                            Height = 3.0,
                            SideLength = 7.0
                        });
                });

            modelBuilder.Entity("DataAcessLayer.ModelsShapes.Triangle", b =>
                {
                    b.HasBaseType("DataAcessLayer.ModelsShapes.Shape");

                    b.Property<double>("BaseLength")
                        .HasColumnType("float");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("SideA")
                        .HasColumnType("float");

                    b.Property<double>("SideB")
                        .HasColumnType("float");

                    b.ToTable("Shapes", t =>
                        {
                            t.Property("BaseLength")
                                .HasColumnName("Triangle_BaseLength");

                            t.Property("Height")
                                .HasColumnName("Triangle_Height");
                        });

                    b.HasDiscriminator().HasValue("Triangle");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Area = 12.0,
                            DateCreated = new DateTime(2024, 6, 7, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Perimeter = 16.0,
                            BaseLength = 6.0,
                            Height = 4.0,
                            SideA = 5.0,
                            SideB = 5.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
