// <auto-generated />
using System;
using DataAcessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAcessLayer.Migrations
{
    [DbContext(typeof(AllDbContext))]
    [Migration("20250522193147_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAcessLayer.ModelsCalculator.Calculator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<double>("Operand1")
                        .HasColumnType("float");

                    b.Property<double?>("Operand2")
                        .HasColumnType("float");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<double>("Result")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Calculations");
                });

            modelBuilder.Entity("DataAcessLayer.ModelsRPS.RPS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComputerMove")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePlayed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerMove")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RpsGames");
                });

            modelBuilder.Entity("DataAcessLayer.ModelsShapes.Shape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<double>("Perimeter")
                        .HasColumnType("float");

                    b.Property<string>("ShapeType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Shapes");

                    b.HasDiscriminator<string>("ShapeType").HasValue("Shape");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DataAcessLayer.ModelsShapes.Parallelogram", b =>
                {
                    b.HasBaseType("DataAcessLayer.ModelsShapes.Shape");

                    b.Property<double>("BaseLength")
                        .HasColumnType("float");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("SideLength")
                        .HasColumnType("float");

                    b.ToTable("Shapes", t =>
                        {
                            t.Property("Height")
                                .HasColumnName("Parallelogram_Height");

                            t.Property("SideLength")
                                .HasColumnName("Parallelogram_SideLength");
                        });

                    b.HasDiscriminator().HasValue("Parallelogram");
                });

            modelBuilder.Entity("DataAcessLayer.ModelsShapes.Rectangle", b =>
                {
                    b.HasBaseType("DataAcessLayer.ModelsShapes.Shape");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Rectangle");
                });

            modelBuilder.Entity("DataAcessLayer.ModelsShapes.Rhombus", b =>
                {
                    b.HasBaseType("DataAcessLayer.ModelsShapes.Shape");

                    b.Property<double>("Diagonal1")
                        .HasColumnType("float");

                    b.Property<double>("Diagonal2")
                        .HasColumnType("float");

                    b.Property<double>("SideLength")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Rhombus");
                });

            modelBuilder.Entity("DataAcessLayer.ModelsShapes.Triangle", b =>
                {
                    b.HasBaseType("DataAcessLayer.ModelsShapes.Shape");

                    b.Property<double>("SideA")
                        .HasColumnType("float");

                    b.Property<double>("SideB")
                        .HasColumnType("float");

                    b.Property<double>("SideC")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Triangle");
                });
#pragma warning restore 612, 618
        }
    }
}
